### ISSUE TITLE
Please updata exon index

### ISSUE THREAD

**Issue by skelviper** [zhuakexi/hires-utils#1]
Hi 
Recently i'm changing my pipeline to hg19, could you update a hg19 version of file "bin_10k_FULL_index"?
Thanks.

**Comment by zhuakexi** [comment]
New version use gencode gtf files as exon index. Forget that pre-built index.  Now you give clean_splicing -r gencode.annotation.gtf

When you are changing reference genome, just use gencode.v19.annotation.gtf.gz rather than gencode.v33.annotation.gtf.gz.
